apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: jfrog-platform
  annotations:
    kots.io/when: '{{repl eq (Distribution) "openshift" }}'
spec:
  helmVersion: v3
  chart:
    name: jfrog-platform
    chartVersion: 0.4.1
  values:
    nginx:
      service:
        type: ClusterIP
    artifactory:
      admin:
        username: '{{repl ConfigOption "admin_username"}}'
        password: '{{repl ConfigOption "admin_password"}}'
    xray:
      enabled: repl{{if ConfigOptionEquals "xray_enabled" "1"}}truerepl{{else}}falserepl{{ end}}
    mission-control:
      enabled: repl{{if ConfigOptionEquals "mission_control_enabled" "1"}}truerepl{{ else}}falserepl{{ end}}