apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: jfrog-platform
  annotations:
    kots.io/when: '{{repl eq (Distribution) "openshift" }}'
spec:
  chart:
    name: openshift-artifactory-ha
    chartVersion: 4.13.0

