apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: jfrog-platform
#  annotations:
#    kots.io/when: '{{repl not (eq (Distribution) "openShift") }}'
spec:
  exclude: '{{repl eq (Distribution) "openShift" }}'
  helmVersion: v3
  chart:
    name: jfrog-platform
    chartVersion: 0.4.1
  values:
    artifactory:
      nginx:
        service:
          type: NodePort
      admin:
        username: '{{repl ConfigOption "admin_username"}}'
        password: '{{repl ConfigOption "admin_password"}}'
    xray:
      enabled: repl{{ConfigOption "xray_enabled" | ParseBool}}
    mission-control:
      enabled: repl{{ConfigOption "mission_control_enabled" | ParseBool}}
    distibution:
      enabled: false
    pipelines:
      enabled: false
  optionalValues:
    - when: '{{repl eq (Distribution) "eks" }}'
      values:
        artifactory-ha:
          nginx:
            service:
              type: LoadBalancer