apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-sample
spec:
  groups:
    - name: admin_password
      title: Admin Setup
      items:
        - name: admin_username
          title: Admin Username
          type: text
          default: admin
        - name: admin_password
          title: Admin Password
          type: password
          default: password
    - name: Optional_Components
      title: Artifactory Optional Components
      items:
        - name: distribution
          value: '{{repl Distribution}}'
          hidden: true
        - name: xray_enabled
          title: Enable xray component (security code scanning) 
          type: bool
          default: false 
        - name: mission_control_enabled
          title: Enable Mission control component
          type: bool
          default: false 
        - name: distribution_enabled
          title: Enable distribution component
          type: bool
          default: false 
        - name: pipelines_enabled
          title: Enable pipelines component
          type: bool
          default: false 
        - name: postgres_type
          type: select_one
          title: Postgres
          default: embedded_postgres
          items:
            - name: embedded_postgres
              title: Embedded Postgres
            - name: external_postgres_inline
              title: External Postgres
          when: '{{repl ConfigOptionEquals "mission_control_enabled" "1"}}'
        - name: embedded_postgres_password
          hidden: true
          type: password
          value: "{{repl RandomString 32}}"
        - name: external_postgres_host
          title: Postgres Host
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
          type: text
          default: postgres
        - name: external_postgres_port
          title: Postgres Port
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
          type: text
          default: "5432"
        - name: external_postgres_user
          title: Postgres Username
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
          type: text
          required: true
        - name: external_postgres_password
          title: Postgres Password
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
          type: password
          required: true
        - name: external_postgres_db
          title: Postgres Database
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
          type: text
          default: database