apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config-sample
spec:
  groups:
    - name: admin_password
      title: Admin Setup
      items:
        - name: admin_username
          title: Admin Username
          type: text
          default: admin
        - name: admin_password
          title: Admin Password
          type: password
          default: password
    - name: Optional_Components
      title: Artifactory Optional Components
      items:
        - name: xray_enabled
          title: Enable xray component
          type: bool
          default: false 
        - name: mission_control_enabled
          title: Enable mission control component
          type: bool
          default: false 