apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: example-preflight-checks
spec:
  collectors:
    - postgres:
        collectorName: postgresql
        uri: 'postgresql://{{repl ConfigOption "external_postgres_user"}}:{{repl ConfigOption "external_postgres_password"}}@{{repl ConfigOption "external_postgres_host"}}:{{repl ConfigOption "external_postgres_port"}}/{{repl ConfigOption "external_postgres_db"}}?sslmode={{repl ConfigOption "external_postgres_sslmode"}}'
    analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.12.0"
              message: The application requires at Kubernetes 1.12.0 or later, and recommends 1.15.0.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.15.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.15.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - containerRuntime:
        outcomes:
          - pass:
              when: "== docker"
              message: Docker container runtime was found.
          - pass:
              when: "== containerd"
              message: containerd runtime was found.
          - fail:
              message: Did not find supported container runtime.
    - distribution:
        checkName: Check Kubernetes environment.
        outcomes:
          - fail:
              when: "== docker-desktop"
              message: The application does not support Docker Desktop Clusters
          - fail:
              when: "== microk8s"
              message: The application does not support Microk8s Clusters
          - fail:
              when: "== minikube"
              message: The application does not support Minikube Clusters
          - pass:
              when: "== eks"
              message: EKS is a supported distribution
          - pass:
              when: "== gke"
              message: GKE is a supported distribution
          - pass:
              when: "== aks"
              message: AKS is a supported distribution
          # Will be supported in the future
          - pass:
              when: "== kurl"
              message: KURL is a supported distribution
          - pass:
              when: "== digitalocean"
              message: DigitalOcean is a supported distribution
          - warn:
              message: Unable to determine the distribution of Kubernetes
    - nodeResources:
        checkName: Total CPU Cores in the cluster is 2 or greater
        outcomes:
          - fail:
              when: "sum(cpuCapacity) < 2"
              message: The cluster must contain at least 2 cores
          - warn:
              when: "sum(cpuCapacity) < 4"
              message: It is recommended to have 4 CPU cores in the cluster
          - pass:
              message: Cluster meets the minimum required CPU resources 
    - nodeResources:
        checkName: One node must have 16 GB RAM and 8 CPU Cores
        filters:
          allocatableMemory: 16Gi
          cpuCapacity: "8"
        outcomes:
          - fail:
              when: count() < 1
              message: Cannot find a node with sufficient memory and cpu
          - pass:
              message: Sufficient CPU and memory is available
    - nodeResources:
        checkName: Number of nodes in the cluster
        outcomes:
          - Warn:
              when: count() < 2
              message: Only 1 node identified 
          - Warn:
              when: count() < 5 
              message: it is strongly recommended to run each JFrog product on its own separate server
          - pass:
              when: count() > 4
              message: This cluster has enough nodes.
    - customResourceDefinition:
        customResourceDefinitionName: constrainttemplates.templates.gatekeeper.sh
        checkName: Gatekeeper policy runtime is installed
        outcomes:
          - fail:
              message: Gatekeeper is required for the application, but not found in the cluster.
          - pass:
              message: Found a supported version of Gatekeeper installed and running in the cluster.
    - postgres:
        checkName: Must be PostgreSQL 10.x or later
        collectorName: postgresql
        outcomes:
          - fail:
              when: connected == false
              message: Cannot connect to PostgreSQL server
          - fail:
              when: version < 10.x
              message: The PostgreSQL server must be at least version 10
          - pass:
              message: The PostgreSQL server is ready
     - postgres:
        checkName: Must be PostgreSQL 10.x or later
        collectorName: postgresql
        outcomes:
          - fail:
              when: connected == false
              message: Cannot connect to PostgreSQL server
          - fail:
              when: version < 10.x
              message: The PostgreSQL server must be at least version 10
          - pass:
              message: The PostgreSQL server is ready